module.exports = {
  extend: 'apostrophe-widgets',
  label: 'iFrame',
  addFields: [
    {
      name: 'src',
      label: 'Source URL',
      type: 'url',
      help: 'The URL of the page your want to show in the iframe, always use HTTPS',
      def:'https:/www.google.com',
      required:true
    },
    {
      name: 'title',
      type: 'string',
      label: 'Title for frame',
      // help: 'At this moment not know why you should use this  ',
      required:false
    },
    {
      name: 'width',
      type: 'string',
      label: 'Width',
      help: 'The width of the iframe, for pixels add px at the end of the number e.g 300px, for percent add % at the end of the number e.g. 100% and for view width add "vw" at the end of the number e.g. 90vw will be 90% of the devices view width',
      def:'100%',
      required:false
    },
    {
      name: 'height',
      type: 'string',
      label: 'Height',
      help: 'The height of the iframe, for pixels add px at the end of the number e.g 300px, for percent add % at the end of the number e.g. 100% (not a good idea, use view height) and for view height add "vh" at the end of the number e.g. 100vh will be the height of the devices screen',
      def:'100vh',
      required:true
    },
    {
      name: 'importance',
      type: 'select',
     
      help: 'Sets the importance of loading the content into the iframe, best to leave this at default',
      choices: [
        {
          label: 'Auto Importance',
          value: 'auto'
        },
        {
          label: 'High Importance',
          value: 'high'
        },
        {
          label: 'Low Importance',
          value: 'low'
        }
      ],
     
      required:false
    },
    {
      name: 'name',
      type: 'string',
      label: 'Name',
      help: 'The Name of the iframe use unique values if you have more than one on a page',
      def:'iframe-1',
      required:false
    },
    {
      name: 'allowForms',
      type: 'boolean',
      label: 'Allowed to submit forms?',
      help: 'Allows the resource to submit forms. If this is not used, form submission is blocked',
      def:true,
      required:false
    },
    {
      name: 'addEmbed',
      type: 'boolean',
      label: 'Add the embed attribute',
      help: 'Tells the resource this is to be embeeded in page - useful for google maps',
      def:false,
      required:false
    },
    {
      name: 'allowModals',
      type: 'boolean',
      label: 'Allowed to show blocking widows',
      help: 'Allowed the iframe page to show blocking widow information',
      def:false,
      required:false
    },
    {
      name: 'allowOrientationLock',
      type: 'boolean',
      label: 'Allowed to lock screen orienation',
      help: 'Lets the resource lock the screen orientation',
      def:false,
      required:false
    },
    {
      name: 'allowPointerLock',
      type: 'boolean',
      label: 'Allowed to lock mouse pointer',
      help: 'Lets the resource use the Pointer Lock API',
      def:false,
      required:false
    },
    {
      name: 'allowPopups',
      type: 'boolean',
      label: 'Allowed to create popups',
      help: 'Lets the resource create popup windows',
      def:false,
      required:false
    },
    {
      name: 'allowPopupsToEscapeSandbox',
      type: 'boolean',
      label: 'Allowed to create popups that target other windows and tabs',
      help: 'Allows popups (such as window.open(), target="_blank", or showModalDialog()). If this keyword is not used, the popup will silently fail to open',
      def:false,
      required:false
    },
    {
      name: 'allowPresentation',
      type: 'boolean',
      label: 'Allowed to create presentation session',
      help: 'Lets the resource start a presentation session',
      def:false,
      required:false
    },
    {
      name: 'allowScripts',
      type: 'boolean',
      label: 'Allowed to run scripts',
      help: 'Lets the resource run scripts (but not create popup windows)',
      def:true,
      required:false
    }
    ,
    {
      name: 'allowSameOrigin',
      type: 'boolean',
      label: 'Allowed access to resources for this domain (Allow Same Origin)',
      help: 'Lets the iframe access cookies and local storage for you master origin (your domain), use with caution',
      def:false,
      required:false
    }
    ,
    {
      name: 'addition',
      type: 'string',
      label: 'Additional Allow Parameters',
      help: 'Do not paste in the Allow keyword or Equals sign just the allowed list generated by an iframe generator without quotes',
      def:'',
      required:false
    },
  ]
}
